### ISSUE TITLE
Can't delete empty folders + suggestion

### ISSUE THREAD

**Issue by yuen-li** [DisboxApp/web#1]
For some reason I can't delete empty folders, the "[Delete](https://i.ibb.co/Zxz7fsJ/download-93.png)" button is always greyed out.
Also, is it possible to have a feature where you can generate a download link for sharing?

**Comment by DisboxApp** [comment]
Thank you for the report, seems like the functionality is missing, my bad!
Will add it soon.

About the second request, please open a separate issue for it so it's more organized - but at first glance it seems possible to implement.

Thanks again for the contribution!

**Comment by DisboxApp** [comment]
Fixed!
