### ISSUE TITLE
Can't use  The Chrome extension on Disbox which is hosted by local

### ISSUE THREAD

**Issue by lava114514** [DisboxApp/web#103]
![Screenshot_20240405_134750](https://github.com/DisboxApp/web/assets/87266204/0540657e-9788-443e-aa8e-4dc47c65f761)

**Comment by DisboxApp** [comment]
Hey, this is a limitation of chrome extenstions.
You can see the allowed URLs here:
https://github.com/DisboxApp/extension/blob/master/manifest.json
```json
    "externally_connectable": {
        "matches": ["*://localhost/*", "*://disboxapp.github.io/*"]
    }
```
You should fork the extension and edit that to add your URL :)

**Comment by lava114514** [comment]
But how can i install the patch extension into my broswer?
