### ISSUE TITLE
Expiration time for Attachment URLs decreasing from 14 days to 1 day

### ISSUE THREAD

**Issue by dave9123** [DisboxApp/web#106]
Based on [the message](https://discord.com/channels/613425648685547541/697138785317814292/1230541218266615918) from Discord Developers official server, expiration time for Attachment URLs will be decreasing from 14 days to 1 day.

> # 🔗 Authenticated Attachment URL Parameters Expiration
> 
> The expiration time for Attachment URLs will be decreasing from 14 days to **1 day**. The rollout will happen gradually on a per-attachment basis, so your app will encounter some attachments with a 1-day expiration, and others with a 14-day expiration.
> 
> As noted in [previous announcements](<https://canary.discord.com/channels/613425648685547541/697138785317814292/1200153906563522660>), you should continue using the `ex` URL parameter to determine the expiration time for an attachment URL.

**Comment by DisboxApp** [comment]
Hey, as previously mentioned in #67, this shouldn't be an issue for downloads (as long as they take less than 24 hours) as Disbox doesn't store attachment URLs.
This *will* be a problem for sharing files.

Thanks for sharing the message!
