### ISSUE TITLE
Share files/folders

### ISSUE THREAD

**Issue by pinkosushi** [DisboxApp/web#12]
Being able to share a download link to a file/folder would be really convenient.

**Comment by billyboybob** [comment]
i wonder how this would work to be honest, as well as how to do it securely if its possible.

**Comment by DisboxApp** [comment]
Here's an idea for how to do this:
- An endpoint that receives the actual URLs of the attachments (as query params), and returns JavaScript that downloads those attachments similar to how the regular client downloads them.
- A front-end share button that creates URLs for that endpoint.

This means that this link will always be *permanent* and that *anyone* with that link will be able to download the file. Which is not ideal, but sounds pretty secure to me. What do you think? I think this can work but am willing to also hear other options.

P.S. Another thing to consider is if this endpoint will be on the server or client (which are currently separated). It fits the server side more, but it would be weird to have to share URLs that come from a different host. Doing it in the client side will also add an option to create a nice UI with progress tracking for the file download.
