### ISSUE TITLE
Discord API change breaks Disbox - Fix coming soon

### ISSUE THREAD

**Issue by DigitalSerpant** [DisboxApp/web#128]
Discord recently pushed an update that disables custom names on files when uploaded to discord. My entire Disbox is empty. Based off how Disbox works, does that means Disbox will no longer work?

**Comment by DisboxApp** [comment]
Hey, this shouldn't break Disbox forever. The custom names don't affect disbox functionality. I will work on a fix ASAP, hopefully today. 

Can you provide links on the change?

**Comment by DigitalSerpant** [comment]
I haven't found anyone or any links explaining this but noticed it first hand as when I tried upload a file to Disbox, all my uploaded files were gone and I was unable to upload more. I should also mention the upload and new folder button are greyed out.

**Comment by Agagamand** [comment]
Today, all the files and folders are gone.

![img](https://github.com/user-attachments/assets/d026da9d-b43b-4996-b32b-87337b1e9f45)

**Comment by DisboxApp** [comment]
Hi, 
I resolved the issue.

It doesn't seem to be related to a Discord API change, but to an issue with the metadata server being down.

It is back up now and Disbox is be back up. None of your files from before were affected.

Thanks to everyone for reporting!
