### ISSUE TITLE
Rate limiting causes chunks not to be uploaded

### ISSUE THREAD

**Issue by billyboybob** [DisboxApp/web#13]
Basically what the title says. Sorry for all the screenshots, this was the best way I could explain it.
I tried uploading a big file, about 2.2GB according to windows explorer, just for the fun of it. 
![Screenshot_4964](https://user-images.githubusercontent.com/61484364/201446235-20d95a27-9d9a-40e8-9710-d535946432c9.png)
However... it seems at around 74-75% discord starts to rate limit the webhook.
![Screenshot_4966](https://user-images.githubusercontent.com/61484364/201446316-42d687ea-4766-4a5d-9f6d-1907b926af6c.png)
This causes some chunks to not be uploaded to Discord (there's more not listed in this screenshot)
![Screenshot_4965](https://user-images.githubusercontent.com/61484364/201446359-f0e90cd2-8d4c-4116-b06b-8c1c77d8d36e.png)
Trying to download the file causes it to error out at the 74% mark, with an error stating this:
![Screenshot_4967](https://user-images.githubusercontent.com/61484364/201446407-3fcded17-d439-4cee-85b6-9ed2a410ea5a.png)
It's a bit inconvenient to chunk it into parts then upload those, so is there a way to fix this?

**Comment by DisboxApp** [comment]
Good catch!
It seems like there are 3 possible solutions to this:
1. Limiting the upload speed.
2. Using the `retry_after` parameter **after** the blocked request.
3. Using the `x-ratelimit-*` headers **before** the blocked request.

If there's no penalty on passing the rate limit too often (which I will research about), I'm opting for the second option, as it will be a cleaner and simpler solution imo. What do you think?

Either way, please share your upload speed so we can get a general sense of the rate limit

Thanks!

**Comment by billyboybob** [comment]
Upload speed should be around 125mbps to 150mbps max, but is usually a bit lower than that. Speed test link: https://www.speedtest.net/result/13941504387
After looking those two things up, it does seem like retry_after is a good option. Not really sure though.

**Comment by billyboybob** [comment]
![Screenshot_5087](https://user-images.githubusercontent.com/61484364/207973412-0e26144e-4938-457c-bd5b-e0205bd2747e.png)
Oddly, it was working quite well, but then at around 50% of the file (it's about 11.4 GB) it started doing this again.
Checking the discord channel also shows that chunks are being skipped
(Also, I would review them but I know next to nothing about coding lol)

Link to the file I used is here: https://placedata.reddit.com/data/canvas-history/2022_place_canvas_history.csv.gzip (it's just the 2022 history for the Reddit Place thing)

**Comment by DisboxApp** [comment]
Thank you! I really appreciate your help with this.
I'll invesitgate this and will probably ask you to test a new version.

I suspect the fix might not be perfect because they `x-ratelimit-retry-after` only displays seconds and not milliseconds.

It is weird though, because I would expect it to round up. Just to make sure, you cloned the bugfix/upload-ratelimit branch, right?

**Comment by billyboybob** [comment]
i downloaded the zip from github, but i tried cloning it just now using git (i made sure it was the right branch) and its doing the same thing

**Comment by DisboxApp** [comment]
Thanks again, I'll look into it and let you know!

**Comment by regan-prendergast** [comment]
Just wanted to add, I'm also getting this from trying to download a file.

The error throws a 429 http error code.

![image](https://user-images.githubusercontent.com/54260175/213960933-d07cabe8-e32b-424a-a221-eddf30062176.png)

**Comment by delibrete** [comment]
Just wanted to add, I'm also getting this from trying to download a file.

![image](https://user-images.githubusercontent.com/475241/213961086-0da2bee7-c6c6-445c-988c-aa38595d21ce.png)

**Comment by delibrete** [comment]
The PR #16 for this seems to fix this issue for me.
