### ISSUE TITLE
Discord naming

### ISSUE THREAD

**Issue by kymophobia** [DisboxApp/web#131]
Is it possible to share the file(s) to the discord with the uploaded name or add a feature to edit the file properties to share before sending to Discord?
It's not explanatory while sharing for ex. mouse_driver.zip but looks like 5170_0.

**Comment by DisboxApp** [comment]
The name really shouldn't matter - you're supposed to share it using Disbox which saves the name itself :)

I avoided saving anything other than the file ID for simplicity... don't want to worry about what characters are allowed. If you can find reliable information from Discord on what is allowed and want to open a PR, I can look at it.
