### ISSUE TITLE
[Suggestion] For a nitro users (500MB Files)

### ISSUE THREAD

**Issue by TacOsAuTaBasCo-crypto** [DisboxApp/web#135]
Hello,

I have a request, if possible, but I wonder if we can have a feature (for example, a toggle button) for Nitro users so that instead of files being split into 25MB segments, they could be 500MB instead. This would reduce message spam if we upload only 2GB.

However, since this is a Webhook, I’m not sure if it’s possible.

Thank you very much for your hard work in providing us with this software.

**Comment by DisboxApp** [comment]
I recently got Nitro and just tried this, seems like it doesn't work since it's using Webhooks:
> Failed to upload file: Error: Failed to sendAttachment with status 413: {"message": "Request entity too large", "code": 40005}
