### ISSUE TITLE
Disbox Renames File and Removes File Extension

### ISSUE THREAD

**Issue by JustinR1** [DisboxApp/web#144]
Hey guys

I came across your project while searching for a file sharing/management Discord bot, and it looks like a great tool. However, I’ve encountered two main issues that are affecting its functionality for me:

1. **Disbox Renames Files**
When I upload a file to the Disbox server, it initially shows the correct name and extension. However, once the upload completes and the message posts to the Discord channel, the file is renamed to something arbitrary, like '63815_0.'
 
2. **File Extensions Are Removed**
Additionally, when I download the file, the extension is missing. I can manually rename the file and add the extension (e.g., .PDF), and it works, but this isn’t ideal.

These issues make it challenging to keep track of which files are which and their respective file types. Is this behavior intentional, or am I missing something here?

I'm not sure if this project is still actively being maintained, but I'd figure I would throw a message out there just in case there's a fix.

**Comment by JustinR1** [comment]
Also, I'm no wizard, but this seemed to have worked for me when I made the following changes.

Changes Made:
1. File: disbox-file-manager.js
2. Method: upload
3. Modification: Changed the way filenames are constructed during the upload process to include the original filename and extension.

**Code Before**:
`this.webhookClient.sendAttachment(`${namePrefix}_${index}`, new Blob([chunk]));`

**Code After**:
`this.webhookClient.sendAttachment(`${namePrefix}_${index}_${sourceFile.name}`, new Blob([chunk]));`

**Comment by DisboxApp** [comment]
Hey Justin,
The point of Disbox is that you'd be able to view the organized files from Disbox itself. Why would you need to look at them through Discord?

You're not supposed to and wouldn't be able to have an organized view of the files even with the correct files, as:
- Disbox splits files larger than 25MB 
- There is no directory structure

**Comment by JustinR1** [comment]
I guess I don't get the point of it posting to discord if you couldn't download from there? It also changed the file name

**Comment by DisboxApp** [comment]
You download it from Discord, through Disbox's UI!

**Comment by JustinR1** [comment]
Thanks for the clarification! So, just to confirm my understanding: Disbox uses its own UI for accessing and managing files, while Discord acts as the storage backend. If a file exceeds 25MB, Disbox automatically splits it into chunks to comply with Discord's file size limits. When I need to retrieve a file, I can do so through the Disbox UI, which reassembles and downloads it as a single file. Is that correct?

**Comment by DisboxApp** [comment]
Yes! Exactly!

**Comment by JustinR1** [comment]
Pardon the intrusion on my flurry of questions. I wasn't sure how else to get in contact with you guys lol.

How does this benefit over, say, using a free dropbox account? Is it because the code is open source and I could in theory do some cool stuff with it and have more control? In my situation for how I use discord, I probably wouldn't need large files. I'd want to share this folder with others on my discord server to also access.

With Disbox, if I wanted to share the same files with others, I'd need to host it on something like heroku that uses the same webhook as my discord channel, correct? Then they could just access it using the same heroku link?

**Comment by DisboxApp** [comment]
You're alright!

I want to start with a disclaimer that this as a project is not something endorsed by Discord and I don't know if it's allowed. I wouldn't trust Discord to keep this as a running thing forever, or to offer storing files without expiry forever. This project was done for the sake of it, and doesn't intend to replace a commercial product like Dropbox.

To actually answer your question though, you wouldn't need to host anything - just add anyone you want in the folder to the Discord server (with webhook perms), and they could access all the files through the webhook URL just like you. Or simpler, give them the specific webhook URL - if you have multiple webhooks and drives on a single server.

**Comment by JustinR1** [comment]
My original hope was to find a bot that I could add to my private discord channel on my server where myself and some admins could use / commands to upload files and then also use / commands to view said files as well as download them. Initially I thought that was what this was, but it's still pretty cool after you explained how it works. I can't really find what I'm looking for. I liked the idea of being able to view, manage, download all from discord instead of using a separate UI, but I guess they don't exist or don't work anymore. Maybe that's a project I could attempt to create 😂

Thanks for answering my question about webhooks, and thanks for your time! Have a good one.
