### ISSUE TITLE
All my files are gone!

### ISSUE THREAD

**Issue by Shieldowskyy** [DisboxApp/web#24]
Up until a week ago when I went to the Disbox website all my files were visible and I could download and upload them. At the moment the site only shows "No rows" and I can't see ANY of my files! Can anyone help me with this?
![image](https://user-images.githubusercontent.com/32707076/213887504-413112c3-f9de-4db5-bb35-0b3f2f8a5467.png)

**Comment by DisboxApp** [comment]
I'm very sorry to hear!
I need to know some more details to know whats gone wrong.

1. When did this start happening?
2. Do you have the chrome extension?
3. What browser and OS are you using?
4. Are the files still in your Discord channel?
5. Can you press F12, click "Console" and show a screenshot of that?

Feel free to send here your Discord account and I'll message you there so we can solve this quicker.

**Comment by Shieldowskyy** [comment]
1. probably after the last Disbox update
2. yes
3. Microsoft Edge (chromium) / Windows 11
4. yes, they are all in place.
5. 
![image](https://user-images.githubusercontent.com/32707076/213890595-15db00c6-329b-4188-a63a-86702bc7e423.png)

**Comment by DisboxApp** [comment]
This is currently being solved privately on Discord as it doesn't seem to be a bug. If this is happening to anyone else, please share.

**Comment by DisboxApp** [comment]
Issue solved! This was a hard bug fix to find.

The issue was that discord changed the webhook URL from `discord.com` to `discordapp.com`.

Closing this for now and will think of a way to show a warning for this or fix it.
