### ISSUE TITLE
Breaking TOS?

### ISSUE THREAD

**Issue by Mixarar** [DisboxApp/web#29]
Was wondering if this is prohibited by discord?

**Comment by delibrete** [comment]
From my brief read of the TOS, it doesn't seem like this app would be violating the TOS, but Discord reserves the right to deactivate your account for essentially whatever reason they find fit. In fact they don't even need to provide a reason.

They would be concerned with how much impact and stress this project would be having on their servers. As long as things are properly rate-limited and the content being uploaded isn't dubious and/or illegal, I doubt they would have much of a problem with it.

Obviously don't take my word for it though, I'm not a lawyer, that's just my 2 cents.

**Comment by Mixarar** [comment]
Thanks for info!
