### ISSUE TITLE
Read only mode/"keys"

### ISSUE THREAD

**Issue by a8underscore** [DisboxApp/web#3]
hello, this would be great for sharing files, but currently I cannot use it for this as it allows others to delete the shared files, perhaps there is some solution possible?

if we can mount our disbox channels via something like fuse, i could use a webserver to list the files read-only

**Comment by DisboxApp** [comment]
Hey! Thanks for opening this issue!

In theory, if you used some sort of API like we discussed in #6 to set up a FUSE filesystem*, and only provided the users access to the mounted filesystem, you could do more advanced access control for it. 

But, if you plan on giving someone the URL for the webhook itself, there's nothing Disbox can do to prevent them from having any permission you have, as this is a Disbox limit.

I think the only workaround you could do for this, is to simply upload the files again, to a separate, shared drive. I agree this is a hassle, and could take a lot of time if the files are big. Maybe Disbox should implement something in the UI to make that easier and more intuitive, but I don't think there's any way to solve it without having to reupload the file. 

I will keep this open for now, to decide if this is in my scope for the project. Of course, I'd be happy if anyone else wants to, or has a better idea on how to implement it.

*This is currently not in my scope for the project.

**Comment by DisboxApp** [comment]
Closing this for #12 as I already wrote a possible solution there which I didn't think of before.
Forgot about this issue when writing that so I didn't mark as duplicate, sorry.
