### ISSUE TITLE
Can't share or download files

### ISSUE THREAD

**Issue by pinkosushi** [DisboxApp/web#32]
In Chrome, I keep getting the error "Failed to share file: TypeError: Cannot read properties of undefined (reading '0')

**Comment by DisboxApp** [comment]
Hey!
I'm gonna need some more info about the issue:
1. Operating System
2. Chrome version
3. If possible, a screenshot of F12 > Console after you try to share/download.

**Comment by pinkosushi** [comment]
1. Windows 10
2. Version 110.0.5481.178
![image](https://user-images.githubusercontent.com/107224095/223908850-b8e13ba7-bd74-4f15-938e-8211cd0cb4ba.png)

**Comment by DisboxApp** [comment]
In addition, if this is urgent and you want to debug it with me so we can solve it the quickest, feel free to leave your Discord account here and I'll message you :)

**Comment by pinkosushi** [comment]
1. ![image](https://user-images.githubusercontent.com/107224095/224445135-7e43afae-add8-46a3-8bcb-89355e995245.png)
2. This seems to only happen with some certain files that were uploaded a while ago.
3. I'm the only user using the webhook.

**Comment by pinkosushi** [comment]
> In addition, if this is urgent and you want to debug it with me so we can solve it the quickest, feel free to leave your Discord account here and I'll message you :)

lil zippy#4291

**Comment by MiroKopecky** [comment]
hi i have similar issue with downloads but even small size files

example of error:
![image](https://user-images.githubusercontent.com/53955446/226108297-c696c834-d586-4163-9a02-0dbfb821574b.png)

**Comment by DisboxApp** [comment]
Hey @MiroKopecky, your error message is different and is probably caused by something else (and I'm pretty sure I know why), so I'm moving the discussion about it back to #35
