### ISSUE TITLE
Cant download any files bigger than 200-500MB

### ISSUE THREAD

**Issue by Shieldowskyy** [DisboxApp/web#38]
When i try to download some bigger file (bigger than 500MB) i got this error and site is freezing with greyed out buttons
![image](https://user-images.githubusercontent.com/32707076/229528733-03d494de-fcd7-4fc2-b1f9-2400f50093f0.png)

Error is in Polish but translates to something like this: "The enull value is not a snowflake."
Tested on Microsoft Edge (chromium) with DisboxDownloader Addon

**Comment by dave9123** [comment]
It works on Google Chrome

**Comment by DisboxApp** [comment]
Hey, is this still happening? Did changing to google chrome fix this?

**Comment by dave9123** [comment]
Download just fine on my Microsoft EdgeOn Jul 2, 2023 01:48, DisboxApp ***@***.***> wrote:
Hey, is this still happening? Did changing to google chrome fix this?

**Comment by DisboxApp** [comment]
Closing as stale.
