### ISSUE TITLE
Download API error

### ISSUE THREAD

**Issue by dave9123** [DisboxApp/web#39]
`Acess to fetch at 'https://api.allorigins.win/raw?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F1083316848059232296%2F1083317251211542598%2F4752_8' from origin 'https://disboxapp.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`Uncaught (in promise) TypeError: Failed to fetch
    at disbox-file-manager.js:42:18
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at $ (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at Ln (disbox-file-manager.js:41:16)`

**Comment by DisboxApp** [comment]
Hey!
I'm trying to reproduce this error but it seems to work fine for me.

I need some more details:
OS, browser, browser version?

Maybe this was a temporary error? Is this still happening?

Anyhow, as an immediate fix you can just download the extension, which removes the nned to use allOrigins entirely: https://chrome.google.com/webstore/detail/disboxdownloader/jklpfhklkhbfgeencifbmkoiaokeieah

**Comment by dave9123** [comment]
Using the extension, I don't get error anymore. Thanks!

**Comment by dave9123** [comment]
OS: Windows
Browser: Chrome
Browser Version: 112.0.5615.50 (Official Build) (64-bit)
