### ISSUE TITLE
[Suggestion] Use another program with 500mb storage limit per file

### ISSUE THREAD

**Issue by Qaveru** [DisboxApp/web#42]
I know it's not about disbox exactly but I still could think about. Is it worth and possible to use guilded.gg as cloud storage cuz they have 500mb for any file except images(which is 25mb).

**Comment by DisboxApp** [comment]
This is a fork that could be done (However, ideally you'd want a stable company which doesn't delete old files - which I'm not sure guilded is).

As you said though, this isn't exactly about Disbox, and as I don't have any plans of doing this - I'm closing this for now.
