### ISSUE TITLE
Download button not Working 

### ISSUE THREAD

**Issue by ravishing-rono** [DisboxApp/web#48]
I can upload files and everything but after I go to the download link, The button doesn't work at all. I tried with 1kb file to 200mb file, Nothing works

**Comment by DisboxApp** [comment]
Hey, please provide some more information with error messages from F12, browser, OS, etc.
As always, I'm available on Discord so feel free to drop your username here and I'll DM you there and we'll try to solve this :)

**Comment by BreadMaster420** [comment]
He might be using Firefox since the download button doesn't work on it, instead it gives an error
"Uncaught (in promise) TypeError: window.showOpenFilePicker() is not a function".
Not sure if I should open a separate issue tho
anyways this project is pretty cool

**Comment by Amongus6969** [comment]
> He might be using Firefox since the download button doesn't work on it, instead it gives an error "Uncaught (in promise) TypeError: window.showOpenFilePicker() is not a function". Not sure if I should open a separate issue tho anyways this project is pretty cool


`Uncaught (in promise) TypeError: window.showSaveFilePicker is not a function
    e file-utils.js:20
    c runtime.js:63
    _invoke runtime.js:294
    D runtime.js:119
    Babel 4
    $n file-utils.js:8
    Gn file-utils.js:8
    e App.js:234
    c runtime.js:63
    _invoke runtime.js:294
    D runtime.js:119
    Babel 4
    te App.js:228
    t columns.js:95
    c runtime.js:63
    _invoke runtime.js:294
    D runtime.js:119
    Babel 4
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 11
    <anonymous> index.js:22
    <anonymous> index.js:40
    <anonymous> index.js:40
file-utils.js:20:37
`

**Comment by DisboxApp** [comment]
That seems to be the issue. Closing for now as this relates to other issues with cross-browser download APIs.

**Comment by BhavikDodda** [comment]
With the Brave browser, I get the following error when attempting to download: Failed to download file: TypeError: window.showSaveFilePicker is not a function

**Comment by DisboxApp** [comment]
> With the Brave browser, I get the following error when attempting to download: Failed to download file: TypeError: window.showSaveFilePicker is not a function

For brave, see a solution in #35
