### ISSUE TITLE
I can't share a file larger than 1 GB

### ISSUE THREAD

**Issue by CodebreakerDevESP** [DisboxApp/web#49]
Good morning, I have been using Disbox to host files on my friends' servers. Everything is working fine but there is one problem that I am not too happy about that.

When I share a larger file (over, for example, 2.1 GB), the site won't let me share it. I get an error called `Failed to share file: NotAllowedError: Failed to execute 'share' on 'Navigator': Must be handling a user gesture to perform a share request.`

I have been trying in several browsers with Chromium (for example Microsoft Edge or Opera GX) and even with Google Chrome, although it works the first time, but the second and the following attempts it stops working.

I will attach the screenshot of the error in case someone (or the developer of the page) can help.

P.S. I'm using the extension recommended by the developer (DisboxDownloader).

![image](https://github.com/DisboxApp/web/assets/90008679/0d3762a9-a77d-4d54-881e-125e23581847)

**Comment by DisboxApp** [comment]
Hey, this seems to be related to URL size and is currently a known issue. Moving this to #23.
