### ISSUE TITLE
New problem for me

### ISSUE THREAD

**Issue by Masonnexe** [DisboxApp/web#55]
I can't download anything else unless something that is small in size [picture}, if anything that is kinda huge in size it is downloaded but the file had became corrupted and unusable but it seems like it stopped downloading at a certain point and also the buttons will not work after clicking it too all of the sudden.
![image](https://github.com/DisboxApp/web/assets/142742282/967cfc8c-280f-407d-a7de-53ba63e6c536)

**Comment by DisboxApp** [comment]
Hey, can you provide steps for reproducing this?

**Comment by DisboxApp** [comment]
Closing as stale.
