### ISSUE TITLE
upload multiple files

### ISSUE THREAD

**Issue by xnicknamex** [DisboxApp/web#56]
how can i upload multiple files? i know that i cant upload a folder but is it possible to upload multiple files from one folder?

**Comment by DisboxApp** [comment]
Hi, please provide more details on the issue or your discord username so I can message you privately and try to debug the issue with you. :)

**Comment by SploeCyber** [comment]
++ This is a great idea

**Comment by DisboxApp** [comment]
Duplicate of #8
