### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by a8underscore** [DisboxApp/web#6]
This could be sick if automated, it could be used for a lot of solutions such as auto backups (dodgy but better then no backups? xd)

compared to the discord webhook api this could provide folders, auto splitting, and ofc files being viewable in the disbox website

**Comment by WolfDWyc** [comment]
Hey! Thanks for opening this issue!

I agree that could help for a lot of things.
Currently, the [disbox-file-manager.js](https://github.com/DisboxApp/web/blob/master/src/disbox-file-manager.js) file should work as a standalone JavaScript API. 

Do you mean a REST API? 
This would be quite a fast server, as it would need to accept the files themselves, and it would also be less secure as the files would have to go through a 3rd party server (And by 3rd party I mean, not Discord or the user itself), which would also have access to your files.

**Comment by DisboxApp** [comment]
Hey! Thanks for opening this issue!

I agree that could help for a lot of things.
Currently, the disbox-file-manager.js file should work as a standalone JavaScript API.

Do you mean a REST API?
This would be quite a fast server, as it would need to accept the files themselves, and it would also be less secure as the files would have to go through a 3rd party server (And by 3rd party I mean, not Discord or the user itself), which would also have access to your files.
