### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by BestInTest** [DisboxApp/web#67]
Today I came across an article: https://www.bleepingcomputer.com/news/security/discord-will-switch-to-temporary-file-links-to-block-malware-delivery/
Specifically, it's about this part: "all links to files uploaded to Discord servers will expire after 24 hours" and "preventing the use of Discord's CDN for permanent file hosting". Does this mean the end of uploading files to Discord? Are there any workarounds for this?

**Comment by Philhubk98** [comment]
Wow if this is really true I think we might want to consider to quit using Discord if they are going to disable our downloads shared with friends privately! My best advice is to make sure you download anything from your friends sent to you immediately before the next 24 hours! Screw Discord the worst chatting app ever made run and designed by a small team of amateurs who don't know how to make a better app for chatting and only making it for profit milking thanks to Nitro.

**Comment by BestInTest** [comment]
Discord doesn't want to disable sending or sharing files with friends. Everything on Discord will continue to work. The issue is about how Disbox works. If the changes take effect, you'll need to somehow obtain a new file download link once every 24 hours. Most likely, Disbox will have to do this through the Discord API, but it will require changes to the code. I just hope there won't be a rate limit on generating links.

**Comment by DisboxApp** [comment]
Hey everyone, thanks for notifying and discussing this here :)

From an initial look, it appears **this does not affect Disbox**.


Disbox stores message IDs which are still permanent, and fetches a download link when you download the file. This will however mean shared files will only work for up to 24 hours - which is not an issue IMO.

**Comment by tris203** [comment]
I posted about this a month or so ago
https://github.com/DisboxApp/web/discussions/23#discussioncomment-7188746

I don't think it will have too much effect on the way Disbox works, apart from as said, share links might expire after 24 hours...but, I actually don't think its too hard to change the way it works. I have an idea

**Comment by DisboxApp** [comment]
Closing for now. @tris203, feel free to open a discussion or PR with your idea for this
