### ISSUE TITLE
disbox can't read the files from the server anymore

### ISSUE THREAD

**Issue by XXABOM7MDXX505** [DisboxApp/web#7]
so the story is that I uploaded my files as a backup because I want to reinstall my windows, then when I tried to get it from the web of disbox, it was empty but the content is in the server. can you please tell me how to read these files on the server? 
![image](https://user-images.githubusercontent.com/106494563/170892637-5bb907e0-01de-489d-8dd7-379262a7dcf1.png)
![image](https://user-images.githubusercontent.com/106494563/170892647-0a4b4375-b3ed-4d22-8a35-68b419f3b327.png)

**Comment by XXABOM7MDXX505** [comment]
and yes I am using the extension with the webhook  like how the your web said.

**Comment by XXABOM7MDXX505** [comment]
okay i found what made it not reading which is was .dfwe virus what baiscally do is renaming files to xxx.exe.dfwe which make things not working, so metadata.json looks is the core of disbox but the problem i can't edit the name because 7z\zip

**Comment by DisboxApp** [comment]
Hey, sorry I couldn't respond earlier!

I'm glad you could solve the issue yourself, but I'm not really sure what ended up being the problem. I would love if you could explain the problem better. Is this something that can be fixed on Disbox's side?
