### ISSUE TITLE
i keep getting this error when uploading files Failed to upload file: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Pickymarker** [DisboxApp/web#73]
i keep getting this error when uploading files Failed to upload file: TypeError: Failed to fetch

**Comment by DisboxApp** [comment]
Hey, please provide some more info about your usage:

- Are you using Chrome?
- What operating system are you on?
- Are you using the chrome extension?
- Does this happen with every file? If not, what's special about files that this happens to? Are they bigger or have some special name?

**Comment by EL-R1** [comment]
I also have this issue
- I'm using Chrome on Version : `119.0.6045.160 (official build) (64 bits)`
- My OS : Windows
- I have the chrome extension installed but that's it, i just clicked on "upload file"
- Files with this problem are > 700MB

I didn't test the limit, but 250MB is good

**Comment by DisboxApp** [comment]
Try using the extension and Chrome as it's the recommended way.

**Comment by turbodude** [comment]
Same issue here. Windows 11, Vivaldi, extension installed. 
Seems to be happening randomly, although depends on the file size. A 100gb file always results in the error, 10gb files - about every fourth time.
