### ISSUE TITLE
Referring to issue #10 

### ISSUE THREAD

**Issue by Enigma1309** [DisboxApp/web#74]
i want to self host this on my repo but the problem is that idk how to do it, i've done the github pages part but i dont understand the server part, does it mean that i have to host the server somewhere in cloud? is there any free alternative way i can use like github pages for hosting?

**Comment by DisboxApp** [comment]
Unfortunately any server that does more than just serving a website can not be hosted on GitHub pages. I can say that running a disbox server on a VM is very easy and requires almost no resources. If people are interested, maybe I can provide an easy way to host it on something like Vercel. If you're interested in that, please open a separate issue on the server repo.
