### ISSUE TITLE
Failed to download file: TypeError: window.showSaveFilePicker is not a function

### ISSUE THREAD

**Issue by DigitalSerpant** [DisboxApp/web#76]
When I try to download a my file(1.7 GB) it displays the error "Failed to download file: TypeError: window.showSaveFilePicker is not a function" in a alert.

**Comment by MT-276** [comment]
Same Issue. But I only encountered this with mobile.

**Comment by DisboxApp** [comment]
Should work now! Added support for mobile and Firefox. Downloads will be slower though. Working on a solution for that.
