### ISSUE TITLE
'Share' link not working for Mobiles

### ISSUE THREAD

**Issue by MT-276** [DisboxApp/web#77]
The link which is generated after pressing "share" is not working for Mobiles.\
Error Image -
![errorImg](https://github.com/DisboxApp/web/assets/97303250/1511bb69-c3a4-4d7b-860b-7c9c0ea1a2d6)
Context: \
I am trying to share a 2.2 GB .zip file to some of my friends. Unfortunately, some of my friends don't own a laptop. For them this error is displayed. Also, it shows the same error even when "desktop mode" is enabled.\
\
This project is getting a lot of popularity, so I hope the community also does a speedy job of implementing new features and bug fixes.\
Ill also be recommending this to many of my friends as this concept is just superb. Please keep up the good work. 😄

**Comment by DisboxApp** [comment]
Should work now! Keep in mind downloads can be much much slower without the chrome extension. I am still working on fixing that.
