### ISSUE TITLE
suggestion:

### ISSUE THREAD

**Issue by anthony1204** [DisboxApp/web#79]
make the share button open a popup that lets you copy the link or make the share button copy the link as well as open the share menu because on windows 11 i cant copy the link

**Comment by anthony1204** [comment]
could also add direct download link

**Comment by DisboxApp** [comment]
This is what the share button does... If the browser supports a share menu, it will use it. Otherwise, it falls back to copying it to the clipboard.

If this doesn't answer your question, feel free to reopen.
