### ISSUE TITLE
issue: Stop reminding to install chrome extension for firefox

### ISSUE THREAD

**Issue by jollran2005** [DisboxApp/web#84]
I'm using Firefox and am constantly reminded to install the extension for Chrome. I installed the Firefox extension but I'm still getting the prompts.

**Comment by DisboxApp** [comment]
Hey! The Firefox extension is not ready yet. I have un-published it for now.

**Comment by jollran2005** [comment]
> Hey! The Firefox extension is not ready yet. I have un-published it for now.

Thanks for the reply! I understand the firefox extension isn't ready, but would it be possible for the website to stop asking me to install the chrome extension when I'm on firefox?
