### ISSUE TITLE
When i download or share

### ISSUE THREAD

**Issue by Kolhax** [DisboxApp/web#86]
only 1kb file is downloaded, without any content
![image](https://github.com/DisboxApp/web/assets/92904192/907f80ef-b559-43df-838d-73863b12190b)
![image](https://github.com/DisboxApp/web/assets/92904192/a2830f5c-e77f-492f-ac2d-c26f2d6e5897)

**Comment by Kolhax** [comment]
i downloaded the chunks on the channel of my webhook and joined the chunks and it worked
idk why it dint worked to download it

**Comment by Kolhax** [comment]
> What browser are you using?

Hey, I mainly use operaGX, but I used chrome

**Comment by olivertd** [comment]
Same issue

**Comment by tris203** [comment]
I cant recreate it

The only thing I can think of is its discord starting to enforce the expiry tokens

Do you have a screenshot of your chrome Dec tools network requests when this happens

**Comment by olivertd** [comment]
> I cant recreate it
> 
> The only thing I can think of is its discord starting to enforce the expiry tokens
> 
> Do you have a screenshot of your chrome Dec tools network requests when this happens

Hello, Problem was fixed by just installing extension. I could not get it to work without the extension

**Comment by starzspirit** [comment]
> > I cant recreate it
> > The only thing I can think of is its discord starting to enforce the expiry tokens
> > Do you have a screenshot of your chrome Dec tools network requests when this happens
> 
> Hello, Problem was fixed by just installing extension. I could not get it to work without the extension

Same thing here. I can get the chunks to properly combine and download using the extension, but not without.

**Comment by Haripritamreddy** [comment]
https://chromewebstore.google.com/detail/disboxdownloader/jklpfhklkhbfgeencifbmkoiaokeieah Is this the extension?
I am using it but still the files are not downloading properly. I am using Brave Browser.

**Comment by DisboxApp** [comment]
It appears the issue was indeed the expiry tokens. Should be fixed now! 
All files should now be downloadable (including those that were uploaded before the bug was fixed).
Sorry for the inconvenience!
