### ISSUE TITLE
Issue to Share

### ISSUE THREAD

**Issue by DieserGhost** [DisboxApp/web#87]
![image](https://github.com/DisboxApp/web/assets/144170441/4dcb4324-ccfc-4453-98d6-096ce947a9d6)

Everytime i share a large file it makes this error.

**Comment by tris203** [comment]
This is a known issue with large shares at the moment. It is fixed in the new WebUI but we are waiting for the merge on that one

**Comment by DisboxApp** [comment]
I added a fallback that just copies the link to your clipboard. Should be fixed now and also helps #23.
