### ISSUE TITLE
Mobile devices support

### ISSUE THREAD

**Issue by osakanaa13** [DisboxApp/web#9]
Please add support on mobile devices.

**Comment by DisboxApp** [comment]
Would really love help for this as I don't think I currently have enough knowledge in frontend development (and especially responsiveness) to do this.

**Comment by letsgoaway-games** [comment]
i think i could help because ive been doing js for a while now
ill make a pull request if i get anything to work

**Comment by DisboxApp** [comment]
@letsgoawaydev Hey, did you make any progress on this? I'll be happy to help if you have any problems with the codebase. Currently refactoring some of it so it'll be easier to develop on.

**Comment by letsgoawaydev** [comment]
i forgot about this comment lol, but ill do some research and get back to you in a few days
