### ISSUE TITLE
Files not downloading properly 

### ISSUE THREAD

**Issue by vnsugadev** [DisboxApp/web#94]
Hi, I uploaded like a 100MB file. When I download it again the download is coming up as a 0.18KB file only. 

I am just using the web app. Is there something wrong I'm doing or?

**Comment by BlobIsBack** [comment]
any fixes ?

**Comment by BlobIsBack** [comment]
I managed to get a file back, I downloaded every part and then renamed it like this (it was a zip file) "test.zip.000" the second one is "test.zip.001" and you rename all files like this. You right click on the first file and then 7-zip>open archive and it opens a gui thing and you click extract archive and set the path to extract

**Comment by DisboxApp** [comment]
Should be fixed now! Had a bug that was caused as a result of a Discord API change.
All files should now be downloadable (including those that were uploaded before the bug was fixed).
Sorry for the inconvenience!

**Comment by Abhinav13246** [comment]
Yeah I Had the same issue.
If you install the extension for dis box then it downloads properly otherwise it just downloads an empty folder.
